# Generated by Django 4.0.2 on 2022-03-01 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedtracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeding',
            name='alfalfa',
            field=models.CharField(default='no alfalfa', max_length=100),
        ),
        migrations.AlterField(
            model_name='feeding',
            name='grain',
            field=models.CharField(default='no grain', max_length=200),
        ),
        migrations.AlterField(
            model_name='feeding',
            name='horse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horses', to='feedtracker.horse'),
        ),
    ]
