# Generated by Django 4.0.2 on 2022-03-01 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedtracker', '0002_alter_feeding_alfalfa_alter_feeding_grain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='horse',
            name='breed',
            field=models.CharField(default='breed unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='horse',
            name='markings',
            field=models.CharField(default='no visible markings', max_length=300),
        ),
    ]
