# Generated by Django 4.0.2 on 2022-03-01 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedtracker', '0003_horse_breed_horse_markings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='horse',
            old_name='owner',
            new_name='user',
        ),
    ]
